[package]
name = "bad-apple-rs"
version = "0.1.0"
edition = "2021"

[dependencies.fbgl]
path = "../fbgl-rs"
features = ["fbdev", "img"]

[dependencies]
crossbeam = "0.8.4"
framebuffer = "0.3.1"
image = "0.25.9"
rodio = "0.21.1"
